version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  bot:
    build: ./Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example

